export const results = [
    {
        id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
        name: "Puneet Bajaj",
        email: "puneetbajaj591@gmail.com",
        university: "Georgia State University",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        labels: ["Location", "Experience", "GPA"],
        new: true,
        position: "Software Engineer Intern",
        last_message: "What is the expected salary for this position? I am very interested in the position and would love to chat with you about it.",
        read: false,
    },
    {
        id: "6c84fb90-12c4-11e1-840d-7b25c5ee775b",
        name: "John Doe",
        email: "johndoe@example.com",
        university: "Georgia Institute of Technology",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        labels: ["Location", "GPA"],
        new: false,
        position: "Software Engineer Intern",
        last_message : "Hey, I saw your profile and I think you would be a great fit for our team. I would love to chat with you about the position and see if you would be interested in joining our team.",
        read: true,
    },
    {
        id: "6c84fb90-12c4-11e1-840d-7b25c5ee775c",
        name: "Jane Doe",
        email: "janedoe@example.com",
        university: "Georgia Southern University",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        labels: ["Location", "Experience"],
        new: false,
        position: "Web Developer",
        last_message : "Hey, I saw your profile and I think you would be a great fit for our team. I would love to chat with you about the position and see if you would be interested in joining our team.",
        read: true,
    },
    {
        id: "6c84fb90-12c4-11e1-840d-7b25c5ee775d",
        name: "John Smith",
        email: "johnsmith@example.com",
        university: "University of Toronto",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        labels: ["Experience", "GPA"],
        new: true,
        position: "Risk Analyst",
        last_message: "Hey, I saw your profile and I think you would be a great fit for our team. I would love to chat with you about the position and see if you would be interested in joining our team.",
        read: true,
    }    
]

export type Results = (typeof results)[number]